app:
    resource: "@AppBundle/Controller/"
    type:     annotation

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

connexion_check:
    path: /connexion_check

logout:
    path: /logout